### PR TITLE
fix: undefined method `exists?' for class File

### PR DESCRIPTION
**Pull request by jhult**
Fixes FusionAuth/homebrew-fusionauth#9

I tested by locally editing the `*.rb` files `/opt/homebrew/Library/Taps/fusionauth/homebrew-fusionauth/Formula`. Installation seemed to work fine with this fix.

### CODE REVIEW

**Comment by Aaron-Ritter** [comment]
testing your changes makes it possible to install but i hit the next issue with 

```
aaron@Mac /o/h/L/T/f/h/Formula (main)> brew services start fusionauth-app
Error: Formula `fusionauth-app` has not implemented #plist, #service or installed a locatable service file
```

**Comment by Aaron-Ritter** [comment]
it requires https://github.com/Homebrew/homebrew-core/issues/79367 on top of these changes

**Review by robotdan — APPROVED** [review]

**Comment by Aaron-Ritter** [comment]
Correct, brew changed away from plist to service which requires according changes. In addition i am checking why the app i received was 1.52.0 through the tap. i am working on a seperate PR at the moment.

**Comment by Aaron-Ritter** [comment]
@robotdan i would create something along the line of https://github.com/FusionAuth/homebrew-fusionauth/pull/16

**Comment by jhult** [comment]
Thanks @robotdan and @Aaron-Ritter.

I'm going to close this in lieu of #16 which includes the changes in this PR.

**Pull request closed without merging**
